# Generated by Django 3.2.9 on 2021-11-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('OTM', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('contract_price', models.IntegerField()),
                ('talaba_hommiyi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homiy.homiy')),
            ],
        ),
    ]
