# Generated by Django 3.2.9 on 2021-11-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homiy', '0001_initial'),
        ('talabaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.CreateModel(
            name='TalabaHomiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajratilgan_suma', models.IntegerField()),
                ('homiy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homiy.homiy')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talabaApp.student')),
            ],
            options={
                'verbose_name_plural': 'TalabalarHomiylari',
            },
        ),
    ]
