# Generated by Django 3.2.9 on 2021-11-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talabaApp', '0002_auto_20211109_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talabahomiy',
            options={'verbose_name_plural': 'Talabalar_Homiylari'},
        ),
    ]
