# Generated by Django 3.2.9 on 2021-11-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talabaApp', '0003_alter_talabahomiy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Studentlar'},
        ),
        migrations.AlterModelTable(
            name='talabahomiy',
            table='Talaba_Homiy',
        ),
    ]
